package Form;

import DB.DBManager;
import agenda.Contacto;
import agenda.Direccion;
import agenda.Email;
import agenda.Telefono;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.text.MaskFormatter;

public class NuevoContactoDgl extends javax.swing.JDialog implements ActionListener {

    private Contacto contactoActual;
    private DBManager db;
    public MaskFormatter formatoTelefono;
    private MainGUI contenerdorTabla;
    private final Calendar calendar = Calendar.getInstance();
    private String currentDate;

    public NuevoContactoDgl(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        updateTime();
        new Timer(1000, this).start();
        db = new DBManager();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void updateTime() {
        calendar.setTimeInMillis(System.currentTimeMillis()); //Update the calendar's time
        currentDate = calendar.getTime().toString();

    }

    @Override
    public void actionPerformed(ActionEvent e) { //A tick happened
        updateTime(); //Update time
        dateLabel.setText(currentDate);
        repaint(); //Update gui
    }

    public Contacto getContactoActual() {
        return contactoActual;
    }

    public void setContactoActual(Contacto contactoActual) {
        this.contactoActual = contactoActual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Datos = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        try{
            formatoTelefono = new MaskFormatter("###-###-####");
        }catch(Exception ex) {

        }
        txtPhone = new JFormattedTextField(formatoTelefono);
        try{
            formatoTelefono = new MaskFormatter("###-###-####");
        }catch(Exception ex) {

        }
        txtMobile = new JFormattedTextField(formatoTelefono);
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblLastName = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        dateLabel = new common.TextLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Datos.setBackground(new java.awt.Color(142, 142, 142));
        Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 0, 51)));
        Datos.setName("Hola"); // NOI18N
        Datos.setPreferredSize(new java.awt.Dimension(450, 440));

        lblName.setText("First Name:");

        lblMobile.setText("Mobile:");

        lblAddress.setText("Address:");

        lblEmail.setText("Email:");

        lblPhone.setText("Phone:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });

        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileKeyTyped(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Lucida Grande", 0, 1)); // NOI18N
        btnSave.setForeground(new java.awt.Color(238, 238, 238));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1412662469_save-32.png"))); // NOI18N
        btnSave.setToolTipText("Save");
        btnSave.setMaximumSize(new java.awt.Dimension(58, 44));
        btnSave.setMinimumSize(new java.awt.Dimension(58, 44));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Lucida Grande", 0, 1)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(238, 238, 238));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1412662544_cancel-32.png"))); // NOI18N
        btnCancel.setToolTipText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Lucida Grande", 0, 1)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(238, 238, 238));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1412662507_editor_trash_delete_recycle_bin_-32.png"))); // NOI18N
        btnDelete.setToolTipText("Delete");
        btnDelete.setMaximumSize(new java.awt.Dimension(58, 44));
        btnDelete.setMinimumSize(new java.awt.Dimension(58, 44));
        btnDelete.setPreferredSize(new java.awt.Dimension(48, 44));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblLastName.setText("Last Name:");

        lblBirthday.setText("Birthday:");

        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        dateLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(lblAddress)
                    .addComponent(lblMobile)
                    .addComponent(lblPhone)
                    .addComponent(lblBirthday)
                    .addComponent(lblLastName)
                    .addComponent(lblName))
                .addGap(35, 35, 35)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtName)
                    .addComponent(txtLastName)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(txtPhone)
                    .addComponent(txtMobile)
                    .addComponent(txtEmail)
                    .addComponent(txtAddress))
                .addContainerGap())
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBirthday)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMobile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancel)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Datos, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Datos, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed

    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.out.println("Action canceled" + " - " + Calendar.getInstance().getTime());
        this.setVisible(false);
        limpiar();
        contenerdorTabla.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        Contacto c = new Contacto();
        c.setNombre(txtName.getText());
        c.setApellido(txtLastName.getText());
        c.setCumpleano((jDateChooser1.getDate()));
        c.setDireccion(new Direccion(txtAddress.getText()));
        c.setTelefono(new Telefono(txtPhone.getText(), txtMobile.getText()));
        c.setEmail(new Email(txtEmail.getText()));
        db = new DBManager();

        if (this.getTitle().equals("Update Contact")) {
            Contacto cc = c;
            cc.setIdContacto(this.getContactoActual().getIdContacto());
            if (db.actualizarContacto(cc)) {
                ImageIcon icon = null;
                icon = new javax.swing.ImageIcon(getClass().getResource("/Images/1412714580_check-circle-outline-48.png"));
                JOptionPane.showMessageDialog(this, "Contact Updated", "Successful", 1, icon);
                this.getContenerdorTabla().buscar();
            }
        } else {
            db.guardarContacto(c);
            ImageIcon icon = null;
            icon = new javax.swing.ImageIcon(getClass().getResource("/Images/1412714580_check-circle-outline-48.png"));
            JOptionPane.showMessageDialog(this, "Contact Saved", "Successful", 1, icon);
            limpiar();
            this.getContenerdorTabla().buscar();
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        ImageIcon icon1 = null;
        icon1 = new javax.swing.ImageIcon(getClass().getResource("/Images/1412716258_help-48.png"));
        int codigo = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this contact ?", "Delete Contact", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, icon1);
        if (codigo == JOptionPane.YES_OPTION) {
            db.borrarContacto(this.getContactoActual());
            ImageIcon icon2 = null;
            icon2 = new javax.swing.ImageIcon(getClass().getResource("/Images/1412714580_check-circle-outline-48.png"));
            JOptionPane.showMessageDialog(this, "Contact Deleted", "Successful", 1, icon2);
            this.getContenerdorTabla().buscar();
            this.setVisible(false);
            contenerdorTabla.setVisible(true);
        } else if (codigo == JOptionPane.NO_OPTION) {
            this.getContenerdorTabla().buscar();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        char c = evt.getKeyChar();
        if ((c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {

        } else if (!(Character.isDigit(c))) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtPhoneKeyTyped

    private void txtMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyTyped
        char c = evt.getKeyChar();
        if ((c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {

        } else if (!(Character.isDigit(c))) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_txtMobileKeyTyped

    public void popular(Contacto c) {
        txtName.setText(c.getNombre());
        txtLastName.setText(c.getApellido());
        jDateChooser1.setDate(c.getCumpleano());
        txtPhone.setText(c.getTelefono().getCasa());
        txtAddress.setText(c.getDireccion().getCasa());
        txtEmail.setText(c.getEmail().getEmailPersonal());
        txtMobile.setText(c.getTelefono().getMovil());
        this.esconderBonton(true);
        this.setContactoActual(c);
    }

    public void limpiar() {
        txtName.setText("");
        txtLastName.setText("");
        jDateChooser1.setDate(null);
        txtPhone.setText("");
        txtAddress.setText("");
        txtEmail.setText("");
        txtMobile.setText("");
    }

    public void esconderBonton(boolean state) {
        btnDelete.setVisible(state);
    }

    public MainGUI getContenerdorTabla() {
        return contenerdorTabla;
    }

    public void setContenerdorTabla(MainGUI contenerdorTabla) {
        this.contenerdorTabla = contenerdorTabla;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoDgl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoDgl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoDgl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoContactoDgl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoContactoDgl dialog = new NuevoContactoDgl(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Datos;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    public common.TextLabel dateLabel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
